version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: marketplace_db
    environment:
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty007
    ports:
      - "5433:5432"
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
    volumes:
      - pg_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    depends_on:
      - postgres
    command:
      - "migrate"
      - "-baselineOnMigrate=true"
    volumes:
      - ./s2/migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/marketplace_db
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: qwerty007
      FLYWAY_BASELINE_VERSION: 1
      FLYWAY_BASELINE_DESCRIPTION: "Initial baseline"
      FLYWAY_SCHEMAS: marketplace

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:qwerty007@postgres:5432/marketplace_db?sslmode=disable"
    volumes:
      - ./queries.yaml:/queries.yaml
    command:
      - "--extend.query-path=/queries.yaml"
      - "--collector.stat_statements"
      - "--collector.stat_statements.query_length=300"
      - "--collector.stat_statements.limit=500"
    ports:
      - "9187:9187"
    depends_on:
      - postgres


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  pg_data: