-- выдача прав ролям
GRANT CONNECT ON DATABASE marketplace_db TO app, readonly, manager;
GRANT USAGE ON SCHEMA marketplace TO app, readonly, manager;

GRANT SELECT, INSERT, UPDATE, DELETE
      ON ALL TABLES IN SCHEMA marketplace TO app;

GRANT SELECT, INSERT, UPDATE
      ON ALL TABLES IN SCHEMA marketplace TO manager;

GRANT SELECT
      ON ALL TABLES IN SCHEMA marketplace TO readonly;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA marketplace TO app, manager;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA marketplace TO readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA marketplace
GRANT USAGE, SELECT ON SEQUENCES TO app, manager;

ALTER DEFAULT PRIVILEGES
IN SCHEMA marketplace
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;

ALTER DEFAULT PRIVILEGES
IN SCHEMA marketplace
GRANT SELECT, INSERT, UPDATE ON TABLES TO manager;

ALTER DEFAULT PRIVILEGES
IN SCHEMA marketplace
GRANT SELECT ON TABLES TO readonly;